# Generated by Django 4.0.3 on 2024-10-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_rif', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=11)),
                ('direccion', models.TextField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.c_status')),
            ],
        ),
    ]
