# Generated by Django 4.0.3 on 2024-10-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_ciudad_cliente_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Observacion',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
