# Generated by Django 4.0.3 on 2024-10-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0004_rename_c_status_statu_alter_statu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['id'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
