# Generated by Django 4.0.3 on 2024-10-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0005_alter_ciudad_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='app_gestion_ciudades',
        ),
    ]
