# Generated by Django 4.0.3 on 2024-10-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0006_alter_ciudad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='app_gestion_clientes',
        ),
        migrations.AlterModelTable(
            name='statu',
            table='app_gestion_status',
        ),
    ]
