# Generated by Django 4.0.3 on 2024-10-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0007_alter_cliente_options_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_rif', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.cliente')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.statu')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'app_gestion_vendedor',
            },
        ),
    ]
