# Generated by Django 4.0.3 on 2024-10-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0008_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statu',
            old_name='status',
            new_name='statu',
        ),
    ]
