# Generated by Django 4.0.3 on 2024-10-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0009_rename_status_statu_statu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendedor',
            table='app_gestion_vendedores',
        ),
    ]
