# Generated by Django 4.0.3 on 2024-10-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0010_alter_vendedor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.vendedor'),
            preserve_default=False,
        ),
    ]
