# Generated by Django 4.0.3 on 2024-10-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0012_siono_remove_cliente_observacion_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siono',
            options={'ordering': ['id'], 'verbose_name': 'Siono', 'verbose_name_plural': 'Siono'},
        ),
    ]
