# Generated by Django 4.0.3 on 2024-10-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0013_alter_siono_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Vendedor',
            new_name='vendedor',
        ),
    ]
