# Generated by Django 4.0.3 on 2024-10-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0014_rename_vendedor_cliente_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
