# Generated by Django 4.0.3 on 2024-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0015_alter_documento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='vencimiento',
            field=models.DateField(default='2024-10-30'),
            preserve_default=False,
        ),
    ]
