# Generated by Django 4.0.3 on 2024-10-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0016_alter_documento_options_documento_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
                'db_table': 'app_gestion_dia',
                'ordering': ['id'],
            },
        ),
    ]
