# Generated by Django 4.0.3 on 2024-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0017_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.CharField(default='Pendiente', max_length=10)),
            ],
            options={
                'verbose_name': 'Iva',
                'verbose_name_plural': 'Iva',
                'db_table': 'app_gestion_iva',
                'ordering': ['id'],
            },
        ),
    ]
