# Generated by Django 4.0.3 on 2024-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0021_documento_abonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='dias_v',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
