# Generated by Django 4.0.3 on 2024-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0022_documento_dias_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-13 14:00'),
            preserve_default=False,
        ),
    ]
