# Generated by Django 4.0.3 on 2024-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0023_cliente_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-13 14:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-13 14:00'),
            preserve_default=False,
        ),
    ]
