# Generated by Django 4.0.3 on 2024-10-14 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0024_control_documento_actualizado_documento_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='', max_length=4)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PagoForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(default='', max_length=40)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000.99)])),
                ('fuente', models.CharField(max_length=30)),
                ('createdo', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(default='-', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.99)])),
                ('monto_procesar', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.99)], verbose_name='Monto a procesar')),
                ('descripcion', models.TextField(blank=True, max_length=250)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.banco')),
                ('forma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.pagoforma')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
