# Generated by Django 4.0.3 on 2024-10-15 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0025_banco_pagoforma_tasa_asiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(default='-', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.99)])),
                ('monto_procesar', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.99)], verbose_name='Monto a procesar')),
                ('descripcion', models.TextField(blank=True, max_length=250)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.cliente')),
                ('forma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.pagoforma')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'app_gestion_pagos',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Asiento',
        ),
    ]
