# Generated by Django 4.0.3 on 2024-10-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0026_pago_delete_asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoforma',
            name='forma',
            field=models.CharField(default='', max_length=40, verbose_name='Forma de pago'),
        ),
    ]
