# Generated by Django 4.0.3 on 2024-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0027_alter_pagoforma_forma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='descripcion',
            new_name='observacion',
        ),
        migrations.AlterField(
            model_name='pagoforma',
            name='forma',
            field=models.CharField(default='', max_length=40),
        ),
    ]
