# Generated by Django 4.0.3 on 2024-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0029_pago_actualizado_pago_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='', max_length=4)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('tipo', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
