# Generated by Django 4.0.3 on 2024-10-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0030_bancodestino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='banco',
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.bancodestino'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(max_length=30),
        ),
    ]
