# Generated by Django 4.0.3 on 2024-10-17 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0031_remove_pago_banco_pago_banco_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.99)], verbose_name='Tasa'),
        ),
    ]
