# Generated by Django 4.0.3 on 2024-10-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0035_alter_documento_monto_alter_pago_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='banco_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.bancodestino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
