# Generated by Django 4.0.3 on 2024-10-22 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestion', '0036_alter_pago_banco_destino_alter_pago_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
