# Generated by Django 4.0.3 on 2024-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0042_alter_pago_monto_alter_pago_monto_procesar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_procesar',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto en $'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
