# Generated by Django 4.0.3 on 2024-10-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0044_documento_usuario_alter_documento_abonado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='banco_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.bancodestino', verbose_name='Banco destino'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.pagoforma', verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto en Bs.'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_procesar',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto en $'),
        ),
    ]
