# Generated by Django 4.0.3 on 2024-10-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0045_pago_documento_alter_pago_banco_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='documento',
        ),
    ]
