# Generated by Django 4.0.3 on 2024-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0046_remove_pago_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pago',
            field=models.IntegerField(default=0),
        ),
    ]
