# Generated by Django 4.0.3 on 2024-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0048_remove_documento_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
