# Generated by Django 4.0.3 on 2024-10-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0049_alter_documento_abonado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dias_v',
            field=models.IntegerField(default=0),
        ),
    ]
