# Generated by Django 4.0.3 on 2024-10-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0050_alter_documento_dias_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('doc_ref', models.CharField(max_length=30)),
                ('forma', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.cliente')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'app_gestion_asientos',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
