# Generated by Django 4.0.3 on 2024-10-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0051_asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.pagoforma'),
        ),
    ]
