# Generated by Django 4.0.3 on 2024-10-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0052_alter_asiento_forma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asiento',
        ),
    ]
