# Generated by Django 4.0.3 on 2024-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0055_alter_pago_monto_alter_pago_monto_procesar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
