# Generated by Django 4.0.3 on 2024-10-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0056_alter_documento_abonado_alter_documento_monto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dia',
            table='app_gestion_dias',
        ),
    ]
