# Generated by Django 4.0.3 on 2024-11-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0057_alter_dia_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='documento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
