# Generated by Django 4.0.3 on 2024-11-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0058_alter_documento_abonado_alter_documento_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='documento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
