# Generated by Django 4.0.3 on 2024-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0059_alter_documento_abonado_alter_documento_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
                'db_table': 'app_gestion_credito',
                'ordering': ['id'],
            },
        ),
    ]
