# Generated by Django 4.0.3 on 2024-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0060_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefijo_ced_rif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_r', models.CharField(max_length=1)),
            ],
        ),
    ]
