# Generated by Django 4.0.3 on 2024-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0061_prefijo_ced_rif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefijo_telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_t', models.CharField(max_length=4)),
            ],
        ),
    ]
