# Generated by Django 4.0.3 on 2024-11-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0062_prefijo_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
    ]
