# Generated by Django 4.0.3 on 2024-11-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0064_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statu',
            name='statu',
            field=models.CharField(max_length=14),
        ),
    ]
