# Generated by Django 4.0.3 on 2024-11-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0065_alter_statu_statu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statu',
            name='statu',
            field=models.CharField(max_length=20),
        ),
    ]
