# Generated by Django 4.0.3 on 2024-11-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0067_alter_cliente_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='ced_rif',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cedula',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
