# Generated by Django 4.0.3 on 2024-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0068_remove_vendedor_ced_rif_vendedor_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ced_rif',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
