# Generated by Django 4.0.3 on 2024-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0070_alter_vendedor_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
