# Generated by Django 4.0.3 on 2024-11-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0071_alter_documento_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_procesar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto en $')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.documento')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.pago')),
            ],
        ),
    ]
