# Generated by Django 4.0.3 on 2024-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0072_pago_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_detalle',
            name='monto_procesar',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
