# Generated by Django 4.0.3 on 2024-11-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0073_alter_pago_detalle_monto_procesar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
