# Generated by Django 4.0.3 on 2024-11-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0074_remove_cliente_ciudad_remove_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.ciudad'),
            preserve_default=False,
        ),
    ]
