# Generated by Django 4.0.3 on 2024-11-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0078_documento_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
