# Generated by Django 4.0.3 on 2024-11-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0079_rename_tipo_documento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Condicion',
                'verbose_name_plural': 'Condicion',
                'db_table': 'app_gestion_condicion',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
