# Generated by Django 4.0.3 on 2024-11-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0081_documento_condicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='observacion',
        ),
    ]
