# Generated by Django 4.0.3 on 2024-11-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0082_remove_cliente_observacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
