# Generated by Django 4.0.3 on 2024-11-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0084_alter_vendedor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['ciudad'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
