# Generated by Django 4.0.3 on 2024-11-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0085_alter_ciudad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.iva'),
        ),
    ]
