# Generated by Django 4.0.3 on 2024-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0086_alter_documento_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='observacion',
            field=models.TextField(default='-', max_length=1000),
        ),
    ]
