# Generated by Django 4.0.3 on 2024-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0088_alter_documento_iva_alter_documento_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='dias_c',
            field=models.IntegerField(default=0),
        ),
    ]
