# Generated by Django 4.0.3 on 2024-11-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0089_documento_dias_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='dias_c',
            new_name='credito',
        ),
    ]
