# Generated by Django 4.0.3 on 2024-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0090_rename_dias_c_documento_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
