# Generated by Django 4.0.3 on 2024-11-19 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0091_ciudad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'CiEstados',
                'db_table': 'app_gestion_estados',
                'ordering': ['estado'],
            },
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.estado'),
        ),
    ]
