# Generated by Django 4.0.3 on 2024-11-19 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestion', '0092_estado_alter_ciudad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-10 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-19 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
