# Generated by Django 4.0.3 on 2024-12-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0096_alter_pago_options_remove_tasa_fuente_tasa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='track',
            field=models.TextField(blank=True),
        ),
    ]
