# Generated by Django 4.0.3 on 2024-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0098_alter_pago_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='actualizado',
            field=models.DateTimeField(),
        ),
    ]
