# Generated by Django 4.0.3 on 2024-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0099_alter_documento_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasa',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='actualizado',
            field=models.DateTimeField(),
        ),
    ]
