# Generated by Django 4.0.3 on 2024-12-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0100_tasa_changes_alter_tasa_actualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='track',
            new_name='seguimiento',
        ),
        migrations.RenameField(
            model_name='tasa',
            old_name='changes',
            new_name='seguimiento',
        ),
    ]
