# Generated by Django 4.0.3 on 2024-12-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0101_rename_track_pago_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
