# Generated by Django 4.0.3 on 2025-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0102_pago_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['vencimiento', 'fecha', 'id'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='seguimiento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, max_length=250, verbose_name='Observación'),
        ),
    ]
