# Generated by Django 4.0.3 on 2025-06-18 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestion', '0105_periodo_ano_alter_periodo_numero_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_comi_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_comi_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='Calculada', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='comision_liquidada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_liquidacion_comision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ComisionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_doc', models.DateField()),
                ('documento', models.CharField(max_length=50)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_impo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comision_calculada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('incluir', models.BooleanField(default=False)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion.comisioncabecera')),
            ],
        ),
    ]
