# Generated by Django 4.0.3 on 2025-06-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0106_comisioncabecera_documento_comision_liquidada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comisionable',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2),
        ),
    ]
