# Generated by Django 4.0.3 on 2025-06-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0106_comisioncabecera_documento_comision_liquidada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='periodo',
            new_name='periodo_id',
        ),
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='vendedor',
            new_name='vendedor_id',
        ),
    ]
