# Generated by Django 4.0.3 on 2025-06-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0107_rename_periodo_comisioncabecera_periodo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='periodo_id',
            new_name='periodo',
        ),
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='vendedor_id',
            new_name='vendedor',
        ),
    ]
