# Generated by Django 4.0.3 on 2025-06-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0107_cliente_comisionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='status',
            field=models.CharField(default='Abierto', max_length=10),
        ),
        migrations.AlterField(
            model_name='comisioncabecera',
            name='status',
            field=models.CharField(default='Calculado', max_length=50),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='numero_semana',
            field=models.IntegerField(),
        ),
    ]
