# Generated by Django 4.0.3 on 2025-06-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0108_periodo_status_alter_comisioncabecera_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisioncabecera',
            name='status',
            field=models.CharField(default='Calculada', max_length=50),
        ),
    ]
