# Generated by Django 4.0.3 on 2025-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0108_rename_periodo_id_comisioncabecera_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisioncabecera',
            name='total_base_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='comisioncabecera',
            name='total_comision_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
