# Generated by Django 4.0.3 on 2025-06-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0109_comisioncabecera_total_base_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='total_base_usd',
            new_name='total_comi_bs',
        ),
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='total_comision_usd',
            new_name='total_comi_usd',
        ),
        migrations.RenameField(
            model_name='comisiondetalle',
            old_name='base_usd',
            new_name='base_impo',
        ),
        migrations.RenameField(
            model_name='comisiondetalle',
            old_name='excluir',
            new_name='incluir',
        ),
        migrations.AddField(
            model_name='comisioncabecera',
            name='status',
            field=models.CharField(default='Calculada', max_length=50),
        ),
        migrations.AlterField(
            model_name='comisiondetalle',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
