# Generated by Django 4.0.3 on 2025-06-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0109_comisioncabecera_total_base_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='total_base_usd',
            new_name='total_comi_bs',
        ),
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='total_comision_usd',
            new_name='total_comis_usd',
        ),
    ]
