# Generated by Django 4.0.3 on 2025-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0109_alter_comisioncabecera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='excedente',
            name='pago_id',
            field=models.IntegerField(default=0),
        ),
    ]
