# Generated by Django 4.0.3 on 2025-06-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0110_rename_total_base_usd_comisioncabecera_total_comi_bs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisiondetalle',
            old_name='base_usd',
            new_name='base_impo',
        ),
    ]
