# Generated by Django 4.0.3 on 2025-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0110_rename_total_base_usd_comisioncabecera_total_comi_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comisionable',
            field=models.CharField(default='Si', max_length=2),
        ),
    ]
