# Generated by Django 4.0.3 on 2025-07-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestion', '0110_excedente_pago_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dias_noComisionables', models.IntegerField(default=0)),
                ('createdo', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField()),
                ('seguimiento', models.TextField(blank=True, null=True)),
                ('modulo', models.TextField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
