# Generated by Django 4.0.3 on 2025-08-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0111_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
    ]
