# Generated by Django 4.0.3 on 2025-06-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0111_rename_base_usd_comisiondetalle_base_impo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisiondetalle',
            old_name='excluir',
            new_name='incluir',
        ),
    ]
