# Generated by Django 4.0.3 on 2025-06-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0111_cliente_comisionable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comisionable',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2),
        ),
    ]
