# Generated by Django 4.0.3 on 2025-06-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0112_rename_excluir_comisiondetalle_incluir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisioncabecera',
            old_name='total_comis_usd',
            new_name='total_comi_usd',
        ),
    ]
