# Generated by Django 4.0.3 on 2025-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0112_alter_cliente_comisionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='estatus',
            field=models.CharField(default='Abierto', max_length=10),
        ),
    ]
