# Generated by Django 4.0.3 on 2025-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0113_rename_total_comis_usd_comisioncabecera_total_comi_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisiondetalle',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
