# Generated by Django 4.0.3 on 2026-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0113_pago_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto en Bs.'),
        ),
    ]
