# Generated by Django 4.0.3 on 2025-06-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0113_periodo_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='estatus',
            new_name='status',
        ),
    ]
