# Generated by Django 4.0.3 on 2025-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0114_alter_comisiondetalle_tasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisioncabecera',
            name='status',
            field=models.CharField(default='Calculada', max_length=50),
        ),
    ]
