# Generated by Django 4.0.3 on 2025-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0114_rename_estatus_periodo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisioncabecera',
            name='status',
            field=models.CharField(default='Calculado', max_length=50),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='numero_semana',
            field=models.IntegerField(),
        ),
    ]
