# Generated by Django 4.0.3 on 2026-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0114_alter_pago_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto IVA'),
        ),
    ]
