# Generated by Django 4.0.3 on 2025-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0115_alter_comisioncabecera_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
