# Generated by Django 4.0.3 on 2026-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0115_pago_monto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_procesar',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Base imponible en $'),
        ),
    ]
