# Generated by Django 4.0.3 on 2026-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0116_alter_pago_monto_procesar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_procesar',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto Base Imponible en $'),
        ),
    ]
