# Generated by Django 4.0.3 on 2026-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0117_alter_pago_monto_procesar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='ajuste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ajuste'),
        ),
    ]
