# Generated by Django 4.0.3 on 2026-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0119_documento_monto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
