# Generated by Django 4.0.3 on 2026-09-19 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestion', '0120_alter_cliente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIvaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_iva', to='app_gestion.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de IVA',
                'verbose_name_plural': 'Pagos de IVA',
                'db_table': 'app_gestion_documento_iva_pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
