# Generated by Django 4.0.3 on 2026-09-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0121_documentoivapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoivapago',
            name='banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion.bancodestino', verbose_name='Banco destino'),
        ),
    ]
