# Generated by Django 4.0.3 on 2026-10-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0122_documentoivapago_banco_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
